apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    my-depl: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      my-depl: nginx
  template:
    metadata:
      labels:
        my-depl: nginx
    spec:
      containers:
        - image: nginx
          name: nginx
          ports:
            - containerPort: 8020
      restartPolicy: Always
