apiVersion: v1
kind: PersistentVolume
metadata:
  name: drkiq-pv
  namespace: ruby
spec:
  storageClassName: drkiq-pv
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/ruby/drkiq
