apiVersion: v1
kind: Service
metadata:
  namespace: ruby
  labels:
    my-service: postgres
  name: postgres
spec:
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
  selector:
    my-service: postgres
